version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: ecommerce_ci_backend
    ports:
      - "3000:4000"

  frontend:
    build:
      context: ./frontend
    container_name: ecommerce_ci_frontend
    ports:
      - "5174:5173"
    depends_on:
      - backend
