version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: ecommerce_ci_backend_a3
    ports:
      - "3000:4000"

  frontend:
    build:
      context: ./frontend
    container_name: ecommerce_ci_frontend_a3
    ports:
      - "5175:5173"
    depends_on:
      - backend
